let bkup = [
    {
        id: "F1FC17JN8-H7MAH0",
        TM: "TM KORFAD",
        Model: "PORTO PR-01",
        Decor: "OAK TOBACCO",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "yes",
        Date: "2022-7-24 Time: 19:5"
    },
    {
        id: "F1FC19D70-5FGH8C",
        TM: "TM KORFAD",
        Model: "PORTO DELUXE PD-03",
        Decor: "OAK TOBACCO",
        Glass: "black",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "yes",
        Date: "2022-7-24 Time: 19:5"
    },
    {
        id: "F1FC1E9C1-141EM3",
        TM: "TM KORFAD",
        Model: "PORTO PR-01",
        Decor: "ESH-WHITE",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-29 Time: 15:59"
    },
    {
        id: "F1GI6FHI0-58513N",
        TM: "TM KORFAD",
        Model: "PORTO PR-01",
        Decor: "VENGE",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-27 Time: 13:56"
    },
    {
        id: "F1HGLJC9J-3097F2",
        TM: "TM KORFAD",
        Model: "PORTO PR-01",
        Decor: "ESH-WHITE",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-29 Time: 15:59"
    },
    {
        id: "F1HGLJF03-5D0C6N",
        TM: "TM KORFAD",
        Model: "PORTO PR-01",
        Decor: "ESH-WHITE",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-29 Time: 15:59"
    },
    {
        id: "F1HGLJMAB-4N7NBK",
        TM: "TM KORFAD",
        Model: "PORTO PR-01",
        Decor: "ESH-WHITE",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-29 Time: 15:59"
    },
    {
        id: "F1I2LCJCB-2E6BEA",
        TM: "TM KORFAD",
        Model: "PORTO PR-01",
        Decor: "VENGE",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-30 Time: 14:5"
    },
    {
        id: "F1I4AI73K-A3FH67",
        TM: "TM LEADOR",
        Model: "NEAPOL",
        Decor: "WHITE MAT",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "yes",
        Date: "2022-7-30 Time: 17:30"
    },
    {
        id: "F1I4AJ3CK-3JB8G0",
        TM: "TM LEADOR",
        Model: "LAZIO",
        Decor: "WHITE MAT",
        Glass: "satin-graphit",
        Design: "classic",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "yes",
        Date: "2022-7-30 Time: 17:31"
    },
    {
        id: "F1I4AK18C-5B0DKI",
        TM: "TM LEADOR",
        Model: "SOVANA",
        Decor: "MOKKO OAK",
        Glass: "black",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-30 Time: 17:31"
    },
    {
        id: "F1I22EABM-47K1K6",
        TM: "TM DARUMI",
        Model: "VELA",
        Decor: "OLS OAK",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-30 Time: 12:20"
    },
    {
        id: "F1I22EAJE-9MEIG8",
        TM: "TM DARUMI",
        Model: "VELA",
        Decor: "OLS OAK",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-30 Time: 12:20"
    },
    {
        id: "F1I22EB2L-43852M",
        TM: "TM DARUMI",
        Model: "VELA",
        Decor: "OLS OAK",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-30 Time: 12:20"
    },
    {
        id: "F1I22EB8M-1C3LKE",
        TM: "TM DARUMI",
        Model: "VELA",
        Decor: "OLS OAK",
        Glass: "satin-white",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "no",
        Date: "2022-7-30 Time: 12:20"
    },
    {
        id: "F1FC1F02H-1N5FGL",
        TM: "TM OMEGA",
        Model: "ART VISION A1",
        Decor: "RAL-7037",
        Glass: "satin-white double sided",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "yes",
        Date: "2022-7-29 Time: 20:8"
    },
    {
        id: "F1FC1FM71-5C68D3",
        TM: "TM OMEGA",
        Model: "LINES L3",
        Decor: "WHITE",
        Glass: "no-glass",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "painted",
        Instock: "yes",
        Date: "2022-7-24 Time: 19:7"
    },
    {
        id: "F1GII98IL-1H3268",
        TM: "TM OMEGA",
        Model: "ART VISION A1",
        Decor: "RAL-7037",
        Glass: "satin-white double sided",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "yes",
        Date: "2022-7-29 Time: 20:11"
    },
    {
        id: "F1I22E51N-37BDGG",
        TM: "TM OMEGA",
        Model: "LINES F5",
        Decor: "RAL-7040",
        Glass: "satin-white double sided",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "yes",
        Date: "2022-7-30 Time: 12:20"
    },
    {
        id: "F1I22E596-51N2FN",
        TM: "TM OMEGA",
        Model: "LINES F5",
        Decor: "RAL-7040",
        Glass: "satin-white double sided",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "yes",
        Date: "2022-7-30 Time: 12:20"
    },
    {
        id: "F1I22E5IE-5CAF54",
        TM: "TM OMEGA",
        Model: "LINES F5",
        Decor: "RAL-7040",
        Glass: "satin-white double sided",
        Design: "modern",
        Lines: "horizontal",
        DecorStyle: "wood",
        Instock: "yes",
        Date: "2022-7-30 Time: 12:20"
    }
]

export { bkup };